#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ygn.models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ygndb")]
	public partial class Ygndb : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCash_balance(Cash_balance instance);
    partial void UpdateCash_balance(Cash_balance instance);
    partial void DeleteCash_balance(Cash_balance instance);
    partial void InsertCash_transaction(Cash_transaction instance);
    partial void UpdateCash_transaction(Cash_transaction instance);
    partial void DeleteCash_transaction(Cash_transaction instance);
    partial void InsertGold_transaction(Gold_transaction instance);
    partial void UpdateGold_transaction(Gold_transaction instance);
    partial void DeleteGold_transaction(Gold_transaction instance);
    partial void InsertPawn_transaction(Pawn_transaction instance);
    partial void UpdatePawn_transaction(Pawn_transaction instance);
    partial void DeletePawn_transaction(Pawn_transaction instance);
    partial void InsertVoucher_code(Voucher_code instance);
    partial void UpdateVoucher_code(Voucher_code instance);
    partial void DeleteVoucher_code(Voucher_code instance);
    #endregion
		
		public Ygndb(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Ygndb(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Ygndb(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Ygndb(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cash_balance> Cash_balances
		{
			get
			{
				return this.GetTable<Cash_balance>();
			}
		}
		
		public System.Data.Linq.Table<Cash_transaction> Cash_transactions
		{
			get
			{
				return this.GetTable<Cash_transaction>();
			}
		}
		
		public System.Data.Linq.Table<Gold_transaction> Gold_transactions
		{
			get
			{
				return this.GetTable<Gold_transaction>();
			}
		}
		
		public System.Data.Linq.Table<Pawn_transaction> Pawn_transactions
		{
			get
			{
				return this.GetTable<Pawn_transaction>();
			}
		}
		
		public System.Data.Linq.Table<Voucher_code> Voucher_codes
		{
			get
			{
				return this.GetTable<Voucher_code>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cash_balance")]
	public partial class Cash_balance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Balance_id;
		
		private System.DateTime _Entry_date;
		
		private decimal _Opening_balance;
		
		private decimal _Closing_balance;
		
		private System.DateTime _Modified_on;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBalance_idChanging(int value);
    partial void OnBalance_idChanged();
    partial void OnEntry_dateChanging(System.DateTime value);
    partial void OnEntry_dateChanged();
    partial void OnOpening_balanceChanging(decimal value);
    partial void OnOpening_balanceChanged();
    partial void OnClosing_balanceChanging(decimal value);
    partial void OnClosing_balanceChanged();
    partial void OnModified_onChanging(System.DateTime value);
    partial void OnModified_onChanged();
    #endregion
		
		public Cash_balance()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="balance_id", Storage="_Balance_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Balance_id
		{
			get
			{
				return this._Balance_id;
			}
			set
			{
				if ((this._Balance_id != value))
				{
					this.OnBalance_idChanging(value);
					this.SendPropertyChanging();
					this._Balance_id = value;
					this.SendPropertyChanged("Balance_id");
					this.OnBalance_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="entry_date", Storage="_Entry_date", DbType="DateTime NOT NULL")]
		public System.DateTime Entry_date
		{
			get
			{
				return this._Entry_date;
			}
			set
			{
				if ((this._Entry_date != value))
				{
					this.OnEntry_dateChanging(value);
					this.SendPropertyChanging();
					this._Entry_date = value;
					this.SendPropertyChanged("Entry_date");
					this.OnEntry_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="opening_balance", Storage="_Opening_balance", DbType="Money NOT NULL")]
		public decimal Opening_balance
		{
			get
			{
				return this._Opening_balance;
			}
			set
			{
				if ((this._Opening_balance != value))
				{
					this.OnOpening_balanceChanging(value);
					this.SendPropertyChanging();
					this._Opening_balance = value;
					this.SendPropertyChanged("Opening_balance");
					this.OnOpening_balanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="closing_balance", Storage="_Closing_balance", DbType="Money NOT NULL")]
		public decimal Closing_balance
		{
			get
			{
				return this._Closing_balance;
			}
			set
			{
				if ((this._Closing_balance != value))
				{
					this.OnClosing_balanceChanging(value);
					this.SendPropertyChanging();
					this._Closing_balance = value;
					this.SendPropertyChanged("Closing_balance");
					this.OnClosing_balanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="modified_on", Storage="_Modified_on", DbType="DateTime NOT NULL")]
		public System.DateTime Modified_on
		{
			get
			{
				return this._Modified_on;
			}
			set
			{
				if ((this._Modified_on != value))
				{
					this.OnModified_onChanging(value);
					this.SendPropertyChanging();
					this._Modified_on = value;
					this.SendPropertyChanged("Modified_on");
					this.OnModified_onChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cash_transaction")]
	public partial class Cash_transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int @__id;
		
		private System.Nullable<System.DateTime> _Transaction_date;
		
		private System.Nullable<byte> _Transaction_type;
		
		private System.Nullable<decimal> _Transaction_amount;
		
		private string _Description;
		
		private System.Nullable<System.DateTime> _Modified_on;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void OnTransaction_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnTransaction_dateChanged();
    partial void OnTransaction_typeChanging(System.Nullable<byte> value);
    partial void OnTransaction_typeChanged();
    partial void OnTransaction_amountChanging(System.Nullable<decimal> value);
    partial void OnTransaction_amountChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnModified_onChanging(System.Nullable<System.DateTime> value);
    partial void OnModified_onChanged();
    #endregion
		
		public Cash_transaction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="__id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int _id
		{
			get
			{
				return this.@__id;
			}
			set
			{
				if ((this.@__id != value))
				{
					this.On_idChanging(value);
					this.SendPropertyChanging();
					this.@__id = value;
					this.SendPropertyChanged("_id");
					this.On_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="transaction_date", Storage="_Transaction_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Transaction_date
		{
			get
			{
				return this._Transaction_date;
			}
			set
			{
				if ((this._Transaction_date != value))
				{
					this.OnTransaction_dateChanging(value);
					this.SendPropertyChanging();
					this._Transaction_date = value;
					this.SendPropertyChanged("Transaction_date");
					this.OnTransaction_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="transaction_type", Storage="_Transaction_type", DbType="TinyInt")]
		public System.Nullable<byte> Transaction_type
		{
			get
			{
				return this._Transaction_type;
			}
			set
			{
				if ((this._Transaction_type != value))
				{
					this.OnTransaction_typeChanging(value);
					this.SendPropertyChanging();
					this._Transaction_type = value;
					this.SendPropertyChanged("Transaction_type");
					this.OnTransaction_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="transaction_amount", Storage="_Transaction_amount", DbType="Money")]
		public System.Nullable<decimal> Transaction_amount
		{
			get
			{
				return this._Transaction_amount;
			}
			set
			{
				if ((this._Transaction_amount != value))
				{
					this.OnTransaction_amountChanging(value);
					this.SendPropertyChanging();
					this._Transaction_amount = value;
					this.SendPropertyChanged("Transaction_amount");
					this.OnTransaction_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="description", Storage="_Description", DbType="NVarChar(800)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="modified_on", Storage="_Modified_on", DbType="DateTime")]
		public System.Nullable<System.DateTime> Modified_on
		{
			get
			{
				return this._Modified_on;
			}
			set
			{
				if ((this._Modified_on != value))
				{
					this.OnModified_onChanging(value);
					this.SendPropertyChanging();
					this._Modified_on = value;
					this.SendPropertyChanged("Modified_on");
					this.OnModified_onChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="gold_transaction")]
	public partial class Gold_transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int @__id;
		
		private System.Nullable<System.DateTime> _Transaction_date;
		
		private System.Nullable<byte> _Transaction_type;
		
		private System.Nullable<decimal> _Transaction_amount;
		
		private string _Description;
		
		private System.Nullable<System.DateTime> _Modified_on;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void OnTransaction_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnTransaction_dateChanged();
    partial void OnTransaction_typeChanging(System.Nullable<byte> value);
    partial void OnTransaction_typeChanged();
    partial void OnTransaction_amountChanging(System.Nullable<decimal> value);
    partial void OnTransaction_amountChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnModified_onChanging(System.Nullable<System.DateTime> value);
    partial void OnModified_onChanged();
    #endregion
		
		public Gold_transaction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="__id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int _id
		{
			get
			{
				return this.@__id;
			}
			set
			{
				if ((this.@__id != value))
				{
					this.On_idChanging(value);
					this.SendPropertyChanging();
					this.@__id = value;
					this.SendPropertyChanged("_id");
					this.On_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="transaction_date", Storage="_Transaction_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Transaction_date
		{
			get
			{
				return this._Transaction_date;
			}
			set
			{
				if ((this._Transaction_date != value))
				{
					this.OnTransaction_dateChanging(value);
					this.SendPropertyChanging();
					this._Transaction_date = value;
					this.SendPropertyChanged("Transaction_date");
					this.OnTransaction_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="transaction_type", Storage="_Transaction_type", DbType="TinyInt")]
		public System.Nullable<byte> Transaction_type
		{
			get
			{
				return this._Transaction_type;
			}
			set
			{
				if ((this._Transaction_type != value))
				{
					this.OnTransaction_typeChanging(value);
					this.SendPropertyChanging();
					this._Transaction_type = value;
					this.SendPropertyChanged("Transaction_type");
					this.OnTransaction_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="transaction_amount", Storage="_Transaction_amount", DbType="Money")]
		public System.Nullable<decimal> Transaction_amount
		{
			get
			{
				return this._Transaction_amount;
			}
			set
			{
				if ((this._Transaction_amount != value))
				{
					this.OnTransaction_amountChanging(value);
					this.SendPropertyChanging();
					this._Transaction_amount = value;
					this.SendPropertyChanged("Transaction_amount");
					this.OnTransaction_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="description", Storage="_Description", DbType="NVarChar(800)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="modified_on", Storage="_Modified_on", DbType="DateTime")]
		public System.Nullable<System.DateTime> Modified_on
		{
			get
			{
				return this._Modified_on;
			}
			set
			{
				if ((this._Modified_on != value))
				{
					this.OnModified_onChanging(value);
					this.SendPropertyChanging();
					this._Modified_on = value;
					this.SendPropertyChanged("Modified_on");
					this.OnModified_onChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="pawn_transaction")]
	public partial class Pawn_transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Voucher_no;
		
		private byte _Voucher_type;
		
		private string _Customer_name;
		
		private string _Customer_nrc;
		
		private string _Customer_address;
		
		private byte _Item_type;
		
		private string _Item_name;
		
		private string _Item_weight;
		
		private decimal _En_amount;
		
		private string _Mm_amount;
		
		private string _Mm_amount_text;
		
		private string _Description;
		
		private System.DateTime _Pawn_date;
		
		private System.DateTime _Receive_date;
		
		private string _User_name;
		
		private bool _Is_received;
		
		private System.Nullable<double> _Interest_rate;
		
		private System.Nullable<System.DateTime> _Modified_on;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVoucher_noChanging(string value);
    partial void OnVoucher_noChanged();
    partial void OnVoucher_typeChanging(byte value);
    partial void OnVoucher_typeChanged();
    partial void OnCustomer_nameChanging(string value);
    partial void OnCustomer_nameChanged();
    partial void OnCustomer_nrcChanging(string value);
    partial void OnCustomer_nrcChanged();
    partial void OnCustomer_addressChanging(string value);
    partial void OnCustomer_addressChanged();
    partial void OnItem_typeChanging(byte value);
    partial void OnItem_typeChanged();
    partial void OnItem_nameChanging(string value);
    partial void OnItem_nameChanged();
    partial void OnItem_weightChanging(string value);
    partial void OnItem_weightChanged();
    partial void OnEn_amountChanging(decimal value);
    partial void OnEn_amountChanged();
    partial void OnMm_amountChanging(string value);
    partial void OnMm_amountChanged();
    partial void OnMm_amount_textChanging(string value);
    partial void OnMm_amount_textChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPawn_dateChanging(System.DateTime value);
    partial void OnPawn_dateChanged();
    partial void OnReceive_dateChanging(System.DateTime value);
    partial void OnReceive_dateChanged();
    partial void OnUser_nameChanging(string value);
    partial void OnUser_nameChanged();
    partial void OnIs_receivedChanging(bool value);
    partial void OnIs_receivedChanged();
    partial void OnInterest_rateChanging(System.Nullable<double> value);
    partial void OnInterest_rateChanged();
    partial void OnModified_onChanging(System.Nullable<System.DateTime> value);
    partial void OnModified_onChanged();
    #endregion
		
		public Pawn_transaction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="voucher_no", Storage="_Voucher_no", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Voucher_no
		{
			get
			{
				return this._Voucher_no;
			}
			set
			{
				if ((this._Voucher_no != value))
				{
					this.OnVoucher_noChanging(value);
					this.SendPropertyChanging();
					this._Voucher_no = value;
					this.SendPropertyChanged("Voucher_no");
					this.OnVoucher_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="voucher_type", Storage="_Voucher_type", DbType="TinyInt NOT NULL")]
		public byte Voucher_type
		{
			get
			{
				return this._Voucher_type;
			}
			set
			{
				if ((this._Voucher_type != value))
				{
					this.OnVoucher_typeChanging(value);
					this.SendPropertyChanging();
					this._Voucher_type = value;
					this.SendPropertyChanged("Voucher_type");
					this.OnVoucher_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="customer_name", Storage="_Customer_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Customer_name
		{
			get
			{
				return this._Customer_name;
			}
			set
			{
				if ((this._Customer_name != value))
				{
					this.OnCustomer_nameChanging(value);
					this.SendPropertyChanging();
					this._Customer_name = value;
					this.SendPropertyChanged("Customer_name");
					this.OnCustomer_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="customer_nrc", Storage="_Customer_nrc", DbType="NVarChar(100)")]
		public string Customer_nrc
		{
			get
			{
				return this._Customer_nrc;
			}
			set
			{
				if ((this._Customer_nrc != value))
				{
					this.OnCustomer_nrcChanging(value);
					this.SendPropertyChanging();
					this._Customer_nrc = value;
					this.SendPropertyChanged("Customer_nrc");
					this.OnCustomer_nrcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="customer_address", Storage="_Customer_address", DbType="NVarChar(300)")]
		public string Customer_address
		{
			get
			{
				return this._Customer_address;
			}
			set
			{
				if ((this._Customer_address != value))
				{
					this.OnCustomer_addressChanging(value);
					this.SendPropertyChanging();
					this._Customer_address = value;
					this.SendPropertyChanged("Customer_address");
					this.OnCustomer_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="item_type", Storage="_Item_type", DbType="TinyInt NOT NULL")]
		public byte Item_type
		{
			get
			{
				return this._Item_type;
			}
			set
			{
				if ((this._Item_type != value))
				{
					this.OnItem_typeChanging(value);
					this.SendPropertyChanging();
					this._Item_type = value;
					this.SendPropertyChanged("Item_type");
					this.OnItem_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="item_name", Storage="_Item_name", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Item_name
		{
			get
			{
				return this._Item_name;
			}
			set
			{
				if ((this._Item_name != value))
				{
					this.OnItem_nameChanging(value);
					this.SendPropertyChanging();
					this._Item_name = value;
					this.SendPropertyChanged("Item_name");
					this.OnItem_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="item_weight", Storage="_Item_weight", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Item_weight
		{
			get
			{
				return this._Item_weight;
			}
			set
			{
				if ((this._Item_weight != value))
				{
					this.OnItem_weightChanging(value);
					this.SendPropertyChanging();
					this._Item_weight = value;
					this.SendPropertyChanged("Item_weight");
					this.OnItem_weightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="en_amount", Storage="_En_amount", DbType="Money NOT NULL")]
		public decimal En_amount
		{
			get
			{
				return this._En_amount;
			}
			set
			{
				if ((this._En_amount != value))
				{
					this.OnEn_amountChanging(value);
					this.SendPropertyChanging();
					this._En_amount = value;
					this.SendPropertyChanged("En_amount");
					this.OnEn_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="mm_amount", Storage="_Mm_amount", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Mm_amount
		{
			get
			{
				return this._Mm_amount;
			}
			set
			{
				if ((this._Mm_amount != value))
				{
					this.OnMm_amountChanging(value);
					this.SendPropertyChanging();
					this._Mm_amount = value;
					this.SendPropertyChanged("Mm_amount");
					this.OnMm_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="mm_amount_text", Storage="_Mm_amount_text", DbType="NVarChar(100)")]
		public string Mm_amount_text
		{
			get
			{
				return this._Mm_amount_text;
			}
			set
			{
				if ((this._Mm_amount_text != value))
				{
					this.OnMm_amount_textChanging(value);
					this.SendPropertyChanging();
					this._Mm_amount_text = value;
					this.SendPropertyChanged("Mm_amount_text");
					this.OnMm_amount_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="description", Storage="_Description", DbType="NVarChar(300)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="pawn_date", Storage="_Pawn_date", DbType="DateTime NOT NULL")]
		public System.DateTime Pawn_date
		{
			get
			{
				return this._Pawn_date;
			}
			set
			{
				if ((this._Pawn_date != value))
				{
					this.OnPawn_dateChanging(value);
					this.SendPropertyChanging();
					this._Pawn_date = value;
					this.SendPropertyChanged("Pawn_date");
					this.OnPawn_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="receive_date", Storage="_Receive_date", DbType="DateTime NOT NULL")]
		public System.DateTime Receive_date
		{
			get
			{
				return this._Receive_date;
			}
			set
			{
				if ((this._Receive_date != value))
				{
					this.OnReceive_dateChanging(value);
					this.SendPropertyChanging();
					this._Receive_date = value;
					this.SendPropertyChanged("Receive_date");
					this.OnReceive_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="user_name", Storage="_User_name", DbType="NVarChar(50)")]
		public string User_name
		{
			get
			{
				return this._User_name;
			}
			set
			{
				if ((this._User_name != value))
				{
					this.OnUser_nameChanging(value);
					this.SendPropertyChanging();
					this._User_name = value;
					this.SendPropertyChanged("User_name");
					this.OnUser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="is_received", Storage="_Is_received", DbType="Bit NOT NULL")]
		public bool Is_received
		{
			get
			{
				return this._Is_received;
			}
			set
			{
				if ((this._Is_received != value))
				{
					this.OnIs_receivedChanging(value);
					this.SendPropertyChanging();
					this._Is_received = value;
					this.SendPropertyChanged("Is_received");
					this.OnIs_receivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="interest_rate", Storage="_Interest_rate", DbType="Float")]
		public System.Nullable<double> Interest_rate
		{
			get
			{
				return this._Interest_rate;
			}
			set
			{
				if ((this._Interest_rate != value))
				{
					this.OnInterest_rateChanging(value);
					this.SendPropertyChanging();
					this._Interest_rate = value;
					this.SendPropertyChanged("Interest_rate");
					this.OnInterest_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="modified_on", Storage="_Modified_on", DbType="DateTime")]
		public System.Nullable<System.DateTime> Modified_on
		{
			get
			{
				return this._Modified_on;
			}
			set
			{
				if ((this._Modified_on != value))
				{
					this.OnModified_onChanging(value);
					this.SendPropertyChanging();
					this._Modified_on = value;
					this.SendPropertyChanged("Modified_on");
					this.OnModified_onChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="voucher_code")]
	public partial class Voucher_code : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Voucher_code_id;
		
		private string _Custom_voucher_code;
		
		private byte _Item_type;
		
		private byte _Voucher_type;
		
		private System.Nullable<System.DateTime> _Modified_on;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVoucher_code_idChanging(string value);
    partial void OnVoucher_code_idChanged();
    partial void OnCustom_voucher_codeChanging(string value);
    partial void OnCustom_voucher_codeChanged();
    partial void OnItem_typeChanging(byte value);
    partial void OnItem_typeChanged();
    partial void OnVoucher_typeChanging(byte value);
    partial void OnVoucher_typeChanged();
    partial void OnModified_onChanging(System.Nullable<System.DateTime> value);
    partial void OnModified_onChanged();
    #endregion
		
		public Voucher_code()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="voucher_code_id", Storage="_Voucher_code_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Voucher_code_id
		{
			get
			{
				return this._Voucher_code_id;
			}
			set
			{
				if ((this._Voucher_code_id != value))
				{
					this.OnVoucher_code_idChanging(value);
					this.SendPropertyChanging();
					this._Voucher_code_id = value;
					this.SendPropertyChanged("Voucher_code_id");
					this.OnVoucher_code_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="custom_voucher_code", Storage="_Custom_voucher_code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Custom_voucher_code
		{
			get
			{
				return this._Custom_voucher_code;
			}
			set
			{
				if ((this._Custom_voucher_code != value))
				{
					this.OnCustom_voucher_codeChanging(value);
					this.SendPropertyChanging();
					this._Custom_voucher_code = value;
					this.SendPropertyChanged("Custom_voucher_code");
					this.OnCustom_voucher_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="item_type", Storage="_Item_type", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte Item_type
		{
			get
			{
				return this._Item_type;
			}
			set
			{
				if ((this._Item_type != value))
				{
					this.OnItem_typeChanging(value);
					this.SendPropertyChanging();
					this._Item_type = value;
					this.SendPropertyChanged("Item_type");
					this.OnItem_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="voucher_type", Storage="_Voucher_type", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte Voucher_type
		{
			get
			{
				return this._Voucher_type;
			}
			set
			{
				if ((this._Voucher_type != value))
				{
					this.OnVoucher_typeChanging(value);
					this.SendPropertyChanging();
					this._Voucher_type = value;
					this.SendPropertyChanged("Voucher_type");
					this.OnVoucher_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="modified_on", Storage="_Modified_on", DbType="DateTime")]
		public System.Nullable<System.DateTime> Modified_on
		{
			get
			{
				return this._Modified_on;
			}
			set
			{
				if ((this._Modified_on != value))
				{
					this.OnModified_onChanging(value);
					this.SendPropertyChanging();
					this._Modified_on = value;
					this.SendPropertyChanged("Modified_on");
					this.OnModified_onChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
